### ISSUE TITLE
Plugin causing "TypeError: Path must be a string" error

### ISSUE THREAD

**Issue by Nathi360** [Telokis/nodebb-plugin-save-plugins#1]
Once the plugin has been activated and the forum is restarted the following error trace occurs:

8/7 23:44:39 [7058] - error: TypeError: Path must be a string. Received { id: 'nodebb-theme-exodus', version: '5.2.6' }
at assertPath (path.js:7:11)
at Object.join (path.js:1211:7)
at Object.Plugins.isInstalled (/home/countach/nodebb/src/plugins/install.js:133:24)
at data.async.waterfall (/home/countach/nodebb/node_modules/nodebb-plugin-save-plugins/lib/installMissing.js:5:40)
at nextTask (/home/countach/nodebb/node_modules/async/dist/async.js:5273:14)
at Object.waterfall (/home/countach/nodebb/node_modules/async/dist/async.js:5283:5)
at /home/countach/nodebb/node_modules/nodebb-plugin-save-plugins/lib/installMissing.js:4:24
at /home/countach/nodebb/node_modules/async/dist/async.js:3060:16
at eachOfArrayLike (/home/countach/nodebb/node_modules/async/dist/async.js:1003:9)
at eachOf (/home/countach/nodebb/node_modules/async/dist/async.js:1051:5)
at Object.eachLimit (/home/countach/nodebb/node_modules/async/dist/async.js:3122:5)
at module.exports (/home/countach/nodebb/node_modules/nodebb-plugin-save-plugins/lib/installMissing.js:3:20)
at data.async.series (/home/countach/nodebb/node_modules/nodebb-plugin-save-plugins/library.js:27:54)
at /home/countach/nodebb/node_modules/async/dist/async.js:3830:24
at replenish (/home/countach/nodebb/node_modules/async/dist/async.js:946:17)
at iterateeCallback (/home/countach/nodebb/node_modules/async/dist/async.js:931:17)
8/7 23:44:39 [7058] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
8/7 23:44:39 [7058] - info: [app] Database connection closed.
8/7 23:44:39 [7058] - info: [app] Web server closed to connections.
8/7 23:44:39 [7058] - info: [app] Shutdown complete.
3 restarts in 10 seconds, most likely an error on startup. Halting.

**Comment by Telokis** [comment]
Hey @Nathi360!
Could you tell me which version of NodeBB you are using, please?

**Comment by r3wt** [comment]
Damn it just happened to me too. I tried to deploy to ubuntu after it worked fine here devving locally

**Comment by Telokis** [comment]
Closing because of the lack of feedback.
